# Generated by Django 5.1.4 on 2025-01-17 20:48

import django.db.models.deletion
import panel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chat_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.BooleanField(default=False)),
                ('balance', models.FloatField(default=0.0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('0', 'archive'), ('1', 'active')], default=1, max_length=1)),
                ('required_subscriptions', models.IntegerField(blank=True, null=True)),
                ('reward', models.FloatField()),
                ('example', models.ImageField(upload_to=panel.models.examples_upload_path)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('channels', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='panel.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('type', models.CharField(choices=[('completed_task', 'выполненное задание'), ('manual_crediting', 'ручное зачисление'), ('disbersement', 'выплата')], max_length=20)),
                ('comment', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Выполнено'), ('rejected', 'Отклонено'), ('missed', 'Пропущенные')], default='pending', max_length=20)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=panel.models.confirmation_upload_path)),
                ('feedback', models.CharField(blank=True, max_length=255, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.user')),
            ],
        ),
    ]
