# Generated by Django 5.1.4 on 2025-01-23 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_usertask_group_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.groups'),
        ),
    ]
