# Generated by Django 5.1.4 on 2025-01-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_task_status_alter_usertask_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bank_details',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.BooleanField(default=True),
        ),
    ]
