# Generated by Django 5.1.4 on 2025-01-18 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_payout_alter_transaction_user_transaction_payout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payout_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='panel.payout'),
        ),
    ]
