# Generated by Django 5.1.4 on 2025-01-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_remove_user_bank_details_remove_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.BooleanField(default=False),
        ),
    ]
