# Generated by Django 5.1.4 on 2025-01-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('completed_task', 'completed_task'), ('manual_crediting', 'manual_crediting'), ('disbersement', 'disbersement')], max_length=20),
        ),
    ]
