# Generated by Django 5.1.4 on 2025-01-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_remove_user_last_activity_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
