# Generated by Django 5.1.4 on 2025-01-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_transaction_payout_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to='panel.user', verbose_name='Приглашенный')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='panel.user', verbose_name='Пригласивший')),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералы',
                'unique_together': {('referrer', 'referred')},
            },
        ),
    ]
