# Generated by Django 5.1.4 on 2025-01-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Выполнено'), ('rejected', 'Отклонено'), ('missed', 'Пропущенные'), ('referral_bonus', 'Реферальный бонус')], default='pending', max_length=20),
        ),
    ]
