# Generated by Django 5.1.4 on 2025-01-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_transaction_comment_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('0', 'archive'), ('1', 'active')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('completed_task', 'выполненное задание'), ('manual_crediting', 'ручное зачисление'), ('disbersement', 'выплата')], max_length=20),
        ),
    ]
