# Generated by Django 5.1.4 on 2025-01-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_usertask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('0', 'archive'), ('1', 'active')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('completed_task', 'выполненное задание'), ('manual_crediting', 'ручное зачисление'), ('disbersement', 'выплата'), ('referral_bonus', 'реферальный бонус')], max_length=20),
        ),
    ]
