# Generated by Django 5.1.4 on 2025-01-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_channels_name_alter_folder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='chat_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
