# Generated by Django 5.1.4 on 2025-01-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_task_status_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'active'), ('0', 'archive')], default=1, max_length=1),
        ),
    ]
