# Generated by Django 5.1.4 on 2025-01-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_task_reminder_end_time_task_reminder_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'active'), ('0', 'archive')], default=1, max_length=1),
        ),
    ]
