# Generated by Django 5.1.4 on 2025-01-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_alter_task_reminder_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('0', 'archive'), ('1', 'active')], default=1, max_length=1),
        ),
    ]
